### ISSUE TITLE
Module structure

### ISSUE THREAD

**Issue by ravager-dk** [PoshCode/PowerShellPracticeAndStyle#157]
An idea would be to add a segment about module structuring like this:
https://ramblingcookiemonster.github.io/Building-A-PowerShell-Module/

**Comment by iRon7** [comment]
Related: [`18740` Best practice: import functions in a module](https://github.com/PowerShell/PowerShell/issues/18740)

**Comment by Jaykul** [comment]
The normal reason for shipping a module as a bunch of separate files is to make it easier to debug. Dot-sourcing lets you get some of the benefits of a module while still keeping all the files separate so you can find things in your editor and deal with breakpoints easily.

Whatever you do, make sure you're not only ever testing individual files instead of the merged module. That change can obscure problems that will pop up when all the files are executed together.

_In my opinion_ you should assume your end-users don't care about debugging, and while you might keep your source files separate _during authoring_, you should merge them all to one file for testing and shipping them, because...

1. Dot-sourcing doesn't work with PowerShell classes
2. Dot-sourcing has minor security risks (especially if you're not listing all the file names in your psm1)
3. Dot-sourcing it slows down module import (particularly when code-signing).  

As a side note: Some organizations are _required_ to run with the "AllSigned" execution policy, or even enforce specific trusted certs -- so even if you don't sign the module yourself, your users may have to sign it before they can use it.

**Comment by Jaykul** [comment]
For what it's worth, @iRon7 if you don't merge all the files, you miss out on 1-3 above, but if you _also_ don't dot-source, you loose ModuleScope, along with the ability to share private functions -- which are powerful and useful features, and the main reasons to build modules in the first place. Honestly, if you _want_ to give those up, you're probably **not writing a module**. 

If you need to ship scripts, you can publish individual scripts. 

If you need to ship a _collection_ of scripts, you could put them all in the module folder, and have a one-liner .psm1:

```PowerShell
$Env:Path += ";$PSScriptRoot"
```

Or export an alias that points at the file (Invoke-Build does that).

This way, the scripts are each _fully_ independent, and can't break each other (at least, not accidentally).

You _could_ also `Import-Module` each ps1 file, or shove them in `NestedModules` in your psd1. Either way, they're stand-alone and don't get in each other's scope (at least, not without intent), and you're more likely to list them all out and prevent someone dropping an extra in without anyone noticing.

**Comment by Jaykul** [comment]
Thoroughly discussed in https://github.com/PoshCode/PowerShellPracticeAndStyle/discussions/171 and all these years later, I think the general idea I proposed there is basically accepted as best practice by the community. We should write that up.
