### ISSUE TITLE
Line Length 80 Characters for Command Prompt?

### ISSUE THREAD

**Issue by ryanspletzer** [PoshCode/PowerShellPracticeAndStyle#47]
I know the formatting guide says to stick to 115 characters b/c the PowerShell host defaults to 120, with some padding in there, etc.

Should we be concerned about the built-in command prompt, which is 80 characters wide by default?

**Comment by Jaykul** [comment]
Heh, line length is one of the most disagreed upon things in code (right next to brace style). :smiling_imp: 

* In Windows 10 that console window is resizable 
* Line length is more about readability in people's text editors (and on GitHub, which is also limited to 120, by default) than about readability in the console.
* We have no vi, emacs, or nano. Making rules to support _reading_ in a console is silly if you can't edit there anyway.

Anyway, after various other discussions, we concluded in #30 that despite it's shortcomings, PowerShell ISE is the main editor being used to write PowerShell, and since it doesn't have any column ruler or guidelines ... that this is one of the guidelines that's really just a suggestion ;-)

In any case, supporting the _defaults_ for the CMD console in previous versions of Windows is really just not going to be enough to swing any votes ;-)

**Comment by ryanspletzer** [comment]
Works for me, I was just thinking about it wanted to make sure it was addressed. Thanks!
