### ISSUE TITLE
Attribute Parameters: Using =$true or Not

### ISSUE THREAD

**Issue by ryanspletzer** [PoshCode/PowerShellPracticeAndStyle#52]
The examples show [Parameter(Mandatory=$true)] but I've also seen plenty others simply do [Parameter(Mandatory)].

Is there a preferred approach?

**Comment by dlwyatt** [comment]
If you need to support PowerShell v2, then you must specify the `=$true` part.  For code that requires v3 or later, I prefer to omit that, but I don't think it matters all that much for a style guide.

**Comment by KirkMunro** [comment]
Language enhancements like these that are non-functional improvements.  With non-functional language improvements, I always err towards sticking with the old syntax until the non-functional improvement is in the lowest version that I or others who use my modules are likely to run into.  For now there is still a lot of PowerShell 2.0 out there so I write my modules using syntax that is understood by 2.0, even if the modules themselves are declared as having a minimum PowerShell version requirement higher than that.  This allows someone working on PowerShell 2.0 to still use my code as an example without scratching their head about syntax errors due to non-functional improvements, while still being completely functional in all other versions that are available.  Once the minimum standard moves up to 3.0, I'll probably adopt the 3.0 non-functional language improvements in my modules.  That's just my approach though.

**Comment by ryanspletzer** [comment]
Perfect, exactly the guidance I was looking for, thanks!
